version: 2
jobs:
  build:
    machine: true
    working_directory: ~/go/src/github.com/fnproject/fdk-node
    # docker:
    #   - image: node:9
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - checkout
      - run:
          name: "test"
          command: |
              ./test.sh
      - run:
          name: Build Docker images
          command: |
              ./build-images.sh 11
              ./build-images.sh 14
      - run:
         name: Login to Docker
         command: |
           if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
               docker login -u $DOCKER_USER -p $DOCKER_PASS
           fi
      # TODO: run npm test
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              # todo: login to npm
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
              ./release.sh
              ./release_images.sh 11
              ./release_images.sh 14
              rm -f .npmrc
            fi
